variables:
  # disable the Gradle daemon for Continuous Integration servers
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

.buildtemplate: &builddefinition
  stage: build
  script:
    - $GRADLE_STRING/bin/gradle --build-cache assembleDist --info
    - mkdir bin
    - cp build/libs/*.jar bin/
    - cp build/distributions/*.zip bin/
  artifacts:
    name: "$CI_COMMIT_REF_NAME-snapshot"
    paths:
      - bin
    expire_in: 1 week
  cache:
    key: "$CI_COMMIT_REF_NAME-$JAVA_VERSION"
    policy: push
    paths:
      - build
      - .gradle

build:linux:jdk8:
  image: registry.gitlab.com/islandoftex/images/javafx-gradle:jdk8-latest
  variables:
    JAVA_VERSION: "8"
  <<: *builddefinition

build:linux:jdk11:
  image: registry.gitlab.com/islandoftex/images/javafx-gradle:jdk11-latest
  variables:
    JAVA_VERSION: "11"
  <<: *builddefinition

.testtemplate: &testdefinition
  stage: test
  script:
    - $GRADLE_STRING/bin/gradle test
  cache:
    key: "$CI_COMMIT_REF_NAME-$JAVA_VERSION"
    policy: pull
    paths:
      - build
      - .gradle

test:linux:jdk8:
  dependencies:
    - build:linux:jdk8
  image: registry.gitlab.com/islandoftex/images/javafx-gradle:jdk8-latest
  variables:
    JAVA_VERSION: "8"
  <<: *testdefinition

test:linux:jdk11:
  dependencies:
    - build:linux:jdk11
  image: registry.gitlab.com/islandoftex/images/javafx-gradle:jdk11-latest
  variables:
    JAVA_VERSION: "11"
  <<: *testdefinition
